#!/usr/bin/python

import sys
import time 
import subprocess

ofile = sys.stdout

def run(command):
  ofile.write("== " + command + " ==\n")
  ofile.flush()
  p = subprocess.Popen(command, shell=True, stdout=ofile, stderr=ofile)
  p.wait()
  ofile.write("\n") 

if __name__ == "__main__":
  run("stap -V")
  run("which stap")
  run("ls -ald `locate -r '/stap$'` `locate -r '/staprun$'`")
  run("printenv | egrep '^PATH=|^LD_LIBRARY_PATH=|^SYSTEMTAP_.*='")
  run("gcc -v")
  run("uname -a")
  run("dmesg | egrep 'stap|systemtap' | tail -n 10")
  run("cat /proc/cpuinfo | egrep 'processor|vendor_id|model name'")
  run(r"rpm -qa --qf %{name}-%{version}-%{release}.%{arch}\\n | egrep 'systemtap|elfutils|kernel|gcc' | sort")
  run(r"egrep 'PROBE|TRACE|MARKER|_DEBUG_' /lib/modules/`uname -r`/build/.config | grep -v not.set | sort | fmt -w 80")
