/* Generated by 'gen-stapmark.h 6' on Thu Apr  6 14:43:42 2006 */

#define STAP_MARK(n) do { \
  static void (*__systemtap_mark_##n##_)(); \
  if (unlikely (__systemtap_mark_##n##_)) \
    (void) (__systemtap_mark_##n##_()); \
} while (0)

#define STAP_MARK_N(n,a1) do { \
  static void (*__systemtap_mark_##n##_N)(int64_t); \
  if (unlikely (__systemtap_mark_##n##_N)) \
    (void) (__systemtap_mark_##n##_N((a1))); \
} while (0)

#define STAP_MARK_S(n,a1) do { \
  static void (*__systemtap_mark_##n##_S)(const char *); \
  if (unlikely (__systemtap_mark_##n##_S)) \
    (void) (__systemtap_mark_##n##_S((a1))); \
} while (0)

#define STAP_MARK_NN(n,a1,a2) do { \
  static void (*__systemtap_mark_##n##_NN)(int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NN)) \
    (void) (__systemtap_mark_##n##_NN((a1),(a2))); \
} while (0)

#define STAP_MARK_SN(n,a1,a2) do { \
  static void (*__systemtap_mark_##n##_SN)(const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SN)) \
    (void) (__systemtap_mark_##n##_SN((a1),(a2))); \
} while (0)

#define STAP_MARK_NS(n,a1,a2) do { \
  static void (*__systemtap_mark_##n##_NS)(int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_NS)) \
    (void) (__systemtap_mark_##n##_NS((a1),(a2))); \
} while (0)

#define STAP_MARK_SS(n,a1,a2) do { \
  static void (*__systemtap_mark_##n##_SS)(const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_SS)) \
    (void) (__systemtap_mark_##n##_SS((a1),(a2))); \
} while (0)

#define STAP_MARK_NNN(n,a1,a2,a3) do { \
  static void (*__systemtap_mark_##n##_NNN)(int64_t,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NNN)) \
    (void) (__systemtap_mark_##n##_NNN((a1),(a2),(a3))); \
} while (0)

#define STAP_MARK_SNN(n,a1,a2,a3) do { \
  static void (*__systemtap_mark_##n##_SNN)(const char *,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SNN)) \
    (void) (__systemtap_mark_##n##_SNN((a1),(a2),(a3))); \
} while (0)

#define STAP_MARK_NSN(n,a1,a2,a3) do { \
  static void (*__systemtap_mark_##n##_NSN)(int64_t,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NSN)) \
    (void) (__systemtap_mark_##n##_NSN((a1),(a2),(a3))); \
} while (0)

#define STAP_MARK_SSN(n,a1,a2,a3) do { \
  static void (*__systemtap_mark_##n##_SSN)(const char *,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SSN)) \
    (void) (__systemtap_mark_##n##_SSN((a1),(a2),(a3))); \
} while (0)

#define STAP_MARK_NNS(n,a1,a2,a3) do { \
  static void (*__systemtap_mark_##n##_NNS)(int64_t,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_NNS)) \
    (void) (__systemtap_mark_##n##_NNS((a1),(a2),(a3))); \
} while (0)

#define STAP_MARK_SNS(n,a1,a2,a3) do { \
  static void (*__systemtap_mark_##n##_SNS)(const char *,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_SNS)) \
    (void) (__systemtap_mark_##n##_SNS((a1),(a2),(a3))); \
} while (0)

#define STAP_MARK_NSS(n,a1,a2,a3) do { \
  static void (*__systemtap_mark_##n##_NSS)(int64_t,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_NSS)) \
    (void) (__systemtap_mark_##n##_NSS((a1),(a2),(a3))); \
} while (0)

#define STAP_MARK_SSS(n,a1,a2,a3) do { \
  static void (*__systemtap_mark_##n##_SSS)(const char *,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_SSS)) \
    (void) (__systemtap_mark_##n##_SSS((a1),(a2),(a3))); \
} while (0)

#define STAP_MARK_NNNN(n,a1,a2,a3,a4) do { \
  static void (*__systemtap_mark_##n##_NNNN)(int64_t,int64_t,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NNNN)) \
    (void) (__systemtap_mark_##n##_NNNN((a1),(a2),(a3),(a4))); \
} while (0)

#define STAP_MARK_SNNN(n,a1,a2,a3,a4) do { \
  static void (*__systemtap_mark_##n##_SNNN)(const char *,int64_t,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SNNN)) \
    (void) (__systemtap_mark_##n##_SNNN((a1),(a2),(a3),(a4))); \
} while (0)

#define STAP_MARK_NSNN(n,a1,a2,a3,a4) do { \
  static void (*__systemtap_mark_##n##_NSNN)(int64_t,const char *,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NSNN)) \
    (void) (__systemtap_mark_##n##_NSNN((a1),(a2),(a3),(a4))); \
} while (0)

#define STAP_MARK_SSNN(n,a1,a2,a3,a4) do { \
  static void (*__systemtap_mark_##n##_SSNN)(const char *,const char *,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SSNN)) \
    (void) (__systemtap_mark_##n##_SSNN((a1),(a2),(a3),(a4))); \
} while (0)

#define STAP_MARK_NNSN(n,a1,a2,a3,a4) do { \
  static void (*__systemtap_mark_##n##_NNSN)(int64_t,int64_t,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NNSN)) \
    (void) (__systemtap_mark_##n##_NNSN((a1),(a2),(a3),(a4))); \
} while (0)

#define STAP_MARK_SNSN(n,a1,a2,a3,a4) do { \
  static void (*__systemtap_mark_##n##_SNSN)(const char *,int64_t,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SNSN)) \
    (void) (__systemtap_mark_##n##_SNSN((a1),(a2),(a3),(a4))); \
} while (0)

#define STAP_MARK_NSSN(n,a1,a2,a3,a4) do { \
  static void (*__systemtap_mark_##n##_NSSN)(int64_t,const char *,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NSSN)) \
    (void) (__systemtap_mark_##n##_NSSN((a1),(a2),(a3),(a4))); \
} while (0)

#define STAP_MARK_SSSN(n,a1,a2,a3,a4) do { \
  static void (*__systemtap_mark_##n##_SSSN)(const char *,const char *,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SSSN)) \
    (void) (__systemtap_mark_##n##_SSSN((a1),(a2),(a3),(a4))); \
} while (0)

#define STAP_MARK_NNNS(n,a1,a2,a3,a4) do { \
  static void (*__systemtap_mark_##n##_NNNS)(int64_t,int64_t,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_NNNS)) \
    (void) (__systemtap_mark_##n##_NNNS((a1),(a2),(a3),(a4))); \
} while (0)

#define STAP_MARK_SNNS(n,a1,a2,a3,a4) do { \
  static void (*__systemtap_mark_##n##_SNNS)(const char *,int64_t,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_SNNS)) \
    (void) (__systemtap_mark_##n##_SNNS((a1),(a2),(a3),(a4))); \
} while (0)

#define STAP_MARK_NSNS(n,a1,a2,a3,a4) do { \
  static void (*__systemtap_mark_##n##_NSNS)(int64_t,const char *,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_NSNS)) \
    (void) (__systemtap_mark_##n##_NSNS((a1),(a2),(a3),(a4))); \
} while (0)

#define STAP_MARK_SSNS(n,a1,a2,a3,a4) do { \
  static void (*__systemtap_mark_##n##_SSNS)(const char *,const char *,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_SSNS)) \
    (void) (__systemtap_mark_##n##_SSNS((a1),(a2),(a3),(a4))); \
} while (0)

#define STAP_MARK_NNSS(n,a1,a2,a3,a4) do { \
  static void (*__systemtap_mark_##n##_NNSS)(int64_t,int64_t,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_NNSS)) \
    (void) (__systemtap_mark_##n##_NNSS((a1),(a2),(a3),(a4))); \
} while (0)

#define STAP_MARK_SNSS(n,a1,a2,a3,a4) do { \
  static void (*__systemtap_mark_##n##_SNSS)(const char *,int64_t,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_SNSS)) \
    (void) (__systemtap_mark_##n##_SNSS((a1),(a2),(a3),(a4))); \
} while (0)

#define STAP_MARK_NSSS(n,a1,a2,a3,a4) do { \
  static void (*__systemtap_mark_##n##_NSSS)(int64_t,const char *,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_NSSS)) \
    (void) (__systemtap_mark_##n##_NSSS((a1),(a2),(a3),(a4))); \
} while (0)

#define STAP_MARK_SSSS(n,a1,a2,a3,a4) do { \
  static void (*__systemtap_mark_##n##_SSSS)(const char *,const char *,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_SSSS)) \
    (void) (__systemtap_mark_##n##_SSSS((a1),(a2),(a3),(a4))); \
} while (0)

#define STAP_MARK_NNNNN(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_NNNNN)(int64_t,int64_t,int64_t,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NNNNN)) \
    (void) (__systemtap_mark_##n##_NNNNN((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_SNNNN(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_SNNNN)(const char *,int64_t,int64_t,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SNNNN)) \
    (void) (__systemtap_mark_##n##_SNNNN((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_NSNNN(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_NSNNN)(int64_t,const char *,int64_t,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NSNNN)) \
    (void) (__systemtap_mark_##n##_NSNNN((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_SSNNN(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_SSNNN)(const char *,const char *,int64_t,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SSNNN)) \
    (void) (__systemtap_mark_##n##_SSNNN((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_NNSNN(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_NNSNN)(int64_t,int64_t,const char *,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NNSNN)) \
    (void) (__systemtap_mark_##n##_NNSNN((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_SNSNN(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_SNSNN)(const char *,int64_t,const char *,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SNSNN)) \
    (void) (__systemtap_mark_##n##_SNSNN((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_NSSNN(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_NSSNN)(int64_t,const char *,const char *,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NSSNN)) \
    (void) (__systemtap_mark_##n##_NSSNN((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_SSSNN(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_SSSNN)(const char *,const char *,const char *,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SSSNN)) \
    (void) (__systemtap_mark_##n##_SSSNN((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_NNNSN(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_NNNSN)(int64_t,int64_t,int64_t,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NNNSN)) \
    (void) (__systemtap_mark_##n##_NNNSN((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_SNNSN(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_SNNSN)(const char *,int64_t,int64_t,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SNNSN)) \
    (void) (__systemtap_mark_##n##_SNNSN((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_NSNSN(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_NSNSN)(int64_t,const char *,int64_t,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NSNSN)) \
    (void) (__systemtap_mark_##n##_NSNSN((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_SSNSN(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_SSNSN)(const char *,const char *,int64_t,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SSNSN)) \
    (void) (__systemtap_mark_##n##_SSNSN((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_NNSSN(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_NNSSN)(int64_t,int64_t,const char *,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NNSSN)) \
    (void) (__systemtap_mark_##n##_NNSSN((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_SNSSN(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_SNSSN)(const char *,int64_t,const char *,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SNSSN)) \
    (void) (__systemtap_mark_##n##_SNSSN((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_NSSSN(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_NSSSN)(int64_t,const char *,const char *,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NSSSN)) \
    (void) (__systemtap_mark_##n##_NSSSN((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_SSSSN(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_SSSSN)(const char *,const char *,const char *,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SSSSN)) \
    (void) (__systemtap_mark_##n##_SSSSN((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_NNNNS(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_NNNNS)(int64_t,int64_t,int64_t,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_NNNNS)) \
    (void) (__systemtap_mark_##n##_NNNNS((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_SNNNS(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_SNNNS)(const char *,int64_t,int64_t,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_SNNNS)) \
    (void) (__systemtap_mark_##n##_SNNNS((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_NSNNS(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_NSNNS)(int64_t,const char *,int64_t,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_NSNNS)) \
    (void) (__systemtap_mark_##n##_NSNNS((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_SSNNS(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_SSNNS)(const char *,const char *,int64_t,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_SSNNS)) \
    (void) (__systemtap_mark_##n##_SSNNS((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_NNSNS(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_NNSNS)(int64_t,int64_t,const char *,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_NNSNS)) \
    (void) (__systemtap_mark_##n##_NNSNS((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_SNSNS(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_SNSNS)(const char *,int64_t,const char *,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_SNSNS)) \
    (void) (__systemtap_mark_##n##_SNSNS((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_NSSNS(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_NSSNS)(int64_t,const char *,const char *,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_NSSNS)) \
    (void) (__systemtap_mark_##n##_NSSNS((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_SSSNS(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_SSSNS)(const char *,const char *,const char *,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_SSSNS)) \
    (void) (__systemtap_mark_##n##_SSSNS((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_NNNSS(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_NNNSS)(int64_t,int64_t,int64_t,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_NNNSS)) \
    (void) (__systemtap_mark_##n##_NNNSS((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_SNNSS(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_SNNSS)(const char *,int64_t,int64_t,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_SNNSS)) \
    (void) (__systemtap_mark_##n##_SNNSS((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_NSNSS(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_NSNSS)(int64_t,const char *,int64_t,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_NSNSS)) \
    (void) (__systemtap_mark_##n##_NSNSS((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_SSNSS(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_SSNSS)(const char *,const char *,int64_t,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_SSNSS)) \
    (void) (__systemtap_mark_##n##_SSNSS((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_NNSSS(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_NNSSS)(int64_t,int64_t,const char *,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_NNSSS)) \
    (void) (__systemtap_mark_##n##_NNSSS((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_SNSSS(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_SNSSS)(const char *,int64_t,const char *,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_SNSSS)) \
    (void) (__systemtap_mark_##n##_SNSSS((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_NSSSS(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_NSSSS)(int64_t,const char *,const char *,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_NSSSS)) \
    (void) (__systemtap_mark_##n##_NSSSS((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_SSSSS(n,a1,a2,a3,a4,a5) do { \
  static void (*__systemtap_mark_##n##_SSSSS)(const char *,const char *,const char *,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_SSSSS)) \
    (void) (__systemtap_mark_##n##_SSSSS((a1),(a2),(a3),(a4),(a5))); \
} while (0)

#define STAP_MARK_NNNNNN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NNNNNN)(int64_t,int64_t,int64_t,int64_t,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NNNNNN)) \
    (void) (__systemtap_mark_##n##_NNNNNN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SNNNNN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SNNNNN)(const char *,int64_t,int64_t,int64_t,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SNNNNN)) \
    (void) (__systemtap_mark_##n##_SNNNNN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NSNNNN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NSNNNN)(int64_t,const char *,int64_t,int64_t,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NSNNNN)) \
    (void) (__systemtap_mark_##n##_NSNNNN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SSNNNN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SSNNNN)(const char *,const char *,int64_t,int64_t,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SSNNNN)) \
    (void) (__systemtap_mark_##n##_SSNNNN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NNSNNN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NNSNNN)(int64_t,int64_t,const char *,int64_t,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NNSNNN)) \
    (void) (__systemtap_mark_##n##_NNSNNN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SNSNNN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SNSNNN)(const char *,int64_t,const char *,int64_t,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SNSNNN)) \
    (void) (__systemtap_mark_##n##_SNSNNN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NSSNNN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NSSNNN)(int64_t,const char *,const char *,int64_t,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NSSNNN)) \
    (void) (__systemtap_mark_##n##_NSSNNN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SSSNNN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SSSNNN)(const char *,const char *,const char *,int64_t,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SSSNNN)) \
    (void) (__systemtap_mark_##n##_SSSNNN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NNNSNN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NNNSNN)(int64_t,int64_t,int64_t,const char *,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NNNSNN)) \
    (void) (__systemtap_mark_##n##_NNNSNN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SNNSNN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SNNSNN)(const char *,int64_t,int64_t,const char *,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SNNSNN)) \
    (void) (__systemtap_mark_##n##_SNNSNN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NSNSNN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NSNSNN)(int64_t,const char *,int64_t,const char *,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NSNSNN)) \
    (void) (__systemtap_mark_##n##_NSNSNN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SSNSNN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SSNSNN)(const char *,const char *,int64_t,const char *,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SSNSNN)) \
    (void) (__systemtap_mark_##n##_SSNSNN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NNSSNN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NNSSNN)(int64_t,int64_t,const char *,const char *,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NNSSNN)) \
    (void) (__systemtap_mark_##n##_NNSSNN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SNSSNN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SNSSNN)(const char *,int64_t,const char *,const char *,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SNSSNN)) \
    (void) (__systemtap_mark_##n##_SNSSNN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NSSSNN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NSSSNN)(int64_t,const char *,const char *,const char *,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NSSSNN)) \
    (void) (__systemtap_mark_##n##_NSSSNN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SSSSNN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SSSSNN)(const char *,const char *,const char *,const char *,int64_t,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SSSSNN)) \
    (void) (__systemtap_mark_##n##_SSSSNN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NNNNSN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NNNNSN)(int64_t,int64_t,int64_t,int64_t,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NNNNSN)) \
    (void) (__systemtap_mark_##n##_NNNNSN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SNNNSN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SNNNSN)(const char *,int64_t,int64_t,int64_t,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SNNNSN)) \
    (void) (__systemtap_mark_##n##_SNNNSN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NSNNSN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NSNNSN)(int64_t,const char *,int64_t,int64_t,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NSNNSN)) \
    (void) (__systemtap_mark_##n##_NSNNSN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SSNNSN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SSNNSN)(const char *,const char *,int64_t,int64_t,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SSNNSN)) \
    (void) (__systemtap_mark_##n##_SSNNSN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NNSNSN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NNSNSN)(int64_t,int64_t,const char *,int64_t,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NNSNSN)) \
    (void) (__systemtap_mark_##n##_NNSNSN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SNSNSN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SNSNSN)(const char *,int64_t,const char *,int64_t,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SNSNSN)) \
    (void) (__systemtap_mark_##n##_SNSNSN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NSSNSN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NSSNSN)(int64_t,const char *,const char *,int64_t,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NSSNSN)) \
    (void) (__systemtap_mark_##n##_NSSNSN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SSSNSN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SSSNSN)(const char *,const char *,const char *,int64_t,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SSSNSN)) \
    (void) (__systemtap_mark_##n##_SSSNSN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NNNSSN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NNNSSN)(int64_t,int64_t,int64_t,const char *,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NNNSSN)) \
    (void) (__systemtap_mark_##n##_NNNSSN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SNNSSN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SNNSSN)(const char *,int64_t,int64_t,const char *,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SNNSSN)) \
    (void) (__systemtap_mark_##n##_SNNSSN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NSNSSN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NSNSSN)(int64_t,const char *,int64_t,const char *,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NSNSSN)) \
    (void) (__systemtap_mark_##n##_NSNSSN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SSNSSN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SSNSSN)(const char *,const char *,int64_t,const char *,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SSNSSN)) \
    (void) (__systemtap_mark_##n##_SSNSSN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NNSSSN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NNSSSN)(int64_t,int64_t,const char *,const char *,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NNSSSN)) \
    (void) (__systemtap_mark_##n##_NNSSSN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SNSSSN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SNSSSN)(const char *,int64_t,const char *,const char *,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SNSSSN)) \
    (void) (__systemtap_mark_##n##_SNSSSN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NSSSSN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NSSSSN)(int64_t,const char *,const char *,const char *,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_NSSSSN)) \
    (void) (__systemtap_mark_##n##_NSSSSN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SSSSSN(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SSSSSN)(const char *,const char *,const char *,const char *,const char *,int64_t); \
  if (unlikely (__systemtap_mark_##n##_SSSSSN)) \
    (void) (__systemtap_mark_##n##_SSSSSN((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NNNNNS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NNNNNS)(int64_t,int64_t,int64_t,int64_t,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_NNNNNS)) \
    (void) (__systemtap_mark_##n##_NNNNNS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SNNNNS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SNNNNS)(const char *,int64_t,int64_t,int64_t,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_SNNNNS)) \
    (void) (__systemtap_mark_##n##_SNNNNS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NSNNNS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NSNNNS)(int64_t,const char *,int64_t,int64_t,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_NSNNNS)) \
    (void) (__systemtap_mark_##n##_NSNNNS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SSNNNS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SSNNNS)(const char *,const char *,int64_t,int64_t,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_SSNNNS)) \
    (void) (__systemtap_mark_##n##_SSNNNS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NNSNNS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NNSNNS)(int64_t,int64_t,const char *,int64_t,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_NNSNNS)) \
    (void) (__systemtap_mark_##n##_NNSNNS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SNSNNS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SNSNNS)(const char *,int64_t,const char *,int64_t,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_SNSNNS)) \
    (void) (__systemtap_mark_##n##_SNSNNS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NSSNNS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NSSNNS)(int64_t,const char *,const char *,int64_t,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_NSSNNS)) \
    (void) (__systemtap_mark_##n##_NSSNNS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SSSNNS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SSSNNS)(const char *,const char *,const char *,int64_t,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_SSSNNS)) \
    (void) (__systemtap_mark_##n##_SSSNNS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NNNSNS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NNNSNS)(int64_t,int64_t,int64_t,const char *,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_NNNSNS)) \
    (void) (__systemtap_mark_##n##_NNNSNS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SNNSNS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SNNSNS)(const char *,int64_t,int64_t,const char *,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_SNNSNS)) \
    (void) (__systemtap_mark_##n##_SNNSNS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NSNSNS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NSNSNS)(int64_t,const char *,int64_t,const char *,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_NSNSNS)) \
    (void) (__systemtap_mark_##n##_NSNSNS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SSNSNS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SSNSNS)(const char *,const char *,int64_t,const char *,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_SSNSNS)) \
    (void) (__systemtap_mark_##n##_SSNSNS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NNSSNS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NNSSNS)(int64_t,int64_t,const char *,const char *,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_NNSSNS)) \
    (void) (__systemtap_mark_##n##_NNSSNS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SNSSNS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SNSSNS)(const char *,int64_t,const char *,const char *,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_SNSSNS)) \
    (void) (__systemtap_mark_##n##_SNSSNS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NSSSNS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NSSSNS)(int64_t,const char *,const char *,const char *,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_NSSSNS)) \
    (void) (__systemtap_mark_##n##_NSSSNS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SSSSNS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SSSSNS)(const char *,const char *,const char *,const char *,int64_t,const char *); \
  if (unlikely (__systemtap_mark_##n##_SSSSNS)) \
    (void) (__systemtap_mark_##n##_SSSSNS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NNNNSS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NNNNSS)(int64_t,int64_t,int64_t,int64_t,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_NNNNSS)) \
    (void) (__systemtap_mark_##n##_NNNNSS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SNNNSS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SNNNSS)(const char *,int64_t,int64_t,int64_t,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_SNNNSS)) \
    (void) (__systemtap_mark_##n##_SNNNSS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NSNNSS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NSNNSS)(int64_t,const char *,int64_t,int64_t,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_NSNNSS)) \
    (void) (__systemtap_mark_##n##_NSNNSS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SSNNSS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SSNNSS)(const char *,const char *,int64_t,int64_t,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_SSNNSS)) \
    (void) (__systemtap_mark_##n##_SSNNSS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NNSNSS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NNSNSS)(int64_t,int64_t,const char *,int64_t,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_NNSNSS)) \
    (void) (__systemtap_mark_##n##_NNSNSS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SNSNSS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SNSNSS)(const char *,int64_t,const char *,int64_t,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_SNSNSS)) \
    (void) (__systemtap_mark_##n##_SNSNSS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NSSNSS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NSSNSS)(int64_t,const char *,const char *,int64_t,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_NSSNSS)) \
    (void) (__systemtap_mark_##n##_NSSNSS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SSSNSS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SSSNSS)(const char *,const char *,const char *,int64_t,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_SSSNSS)) \
    (void) (__systemtap_mark_##n##_SSSNSS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NNNSSS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NNNSSS)(int64_t,int64_t,int64_t,const char *,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_NNNSSS)) \
    (void) (__systemtap_mark_##n##_NNNSSS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SNNSSS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SNNSSS)(const char *,int64_t,int64_t,const char *,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_SNNSSS)) \
    (void) (__systemtap_mark_##n##_SNNSSS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NSNSSS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NSNSSS)(int64_t,const char *,int64_t,const char *,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_NSNSSS)) \
    (void) (__systemtap_mark_##n##_NSNSSS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SSNSSS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SSNSSS)(const char *,const char *,int64_t,const char *,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_SSNSSS)) \
    (void) (__systemtap_mark_##n##_SSNSSS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NNSSSS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NNSSSS)(int64_t,int64_t,const char *,const char *,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_NNSSSS)) \
    (void) (__systemtap_mark_##n##_NNSSSS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SNSSSS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SNSSSS)(const char *,int64_t,const char *,const char *,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_SNSSSS)) \
    (void) (__systemtap_mark_##n##_SNSSSS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_NSSSSS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_NSSSSS)(int64_t,const char *,const char *,const char *,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_NSSSSS)) \
    (void) (__systemtap_mark_##n##_NSSSSS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

#define STAP_MARK_SSSSSS(n,a1,a2,a3,a4,a5,a6) do { \
  static void (*__systemtap_mark_##n##_SSSSSS)(const char *,const char *,const char *,const char *,const char *,const char *); \
  if (unlikely (__systemtap_mark_##n##_SSSSSS)) \
    (void) (__systemtap_mark_##n##_SSSSSS((a1),(a2),(a3),(a4),(a5),(a6))); \
} while (0)

