#!/bin/bash

# Start a systemtap server
#
# Copyright (C) 2008-2011 Red Hat Inc.
#
# This file is part of systemtap, and is free software.  You can
# redistribute it and/or modify it under the terms of the GNU General
# Public License (GPL); either version 2, or (at your option) any
# later version.

# This script attempts to start a systemtap server and echoes the
# process id, if successful.

# Initialize the environment
. ${PKGLIBEXECDIR}stap-env

startup_timeout=20

# start the server
${stap_pkglibexecdir}stap-serverd "$@" </dev/null >/dev/null 2>/dev/null &
server_pid=$!

# Make sure the server is started
for ((attempt=0; $attempt < $startup_timeout; ++attempt))
do
    server_started=0
    avahi_advertising=0

    # Has the server started?
    if ! (ps -e | grep stap-serverd | grep $server_pid) >/dev/null 2>&1; then
	# The stap-serverd script should start right away
	test $server_started = 0 -a $attempt -gt 1 && break
        sleep 1
        continue
    fi
    server_started=1

    # Is avahi advertizing the server?
    if ! (avahi-browse $stap_avahi_service_tag --terminate | \
	  grep "Systemtap Compile Server" | grep $server_pid) \
	>/dev/null 2>&1; then
	sleep 1
	continue
    fi
    avahi_advertising=1

    break; # Server is up and advertised
done

# server did not start?
if test $server_started = 0; then
    echo -n "Unable to start a systemtap server: " >&2
    echo "${stap_pkglibexecdir}stap-serverd did not start" >&2
    exit 1
fi

# Is avahi advertising the server? Warn if not.
if test $avahi_advertising = 0; then
    echo "WARNING: avahi is not advertising the server" >&2
fi

# The server is ready
echo $server_pid
exit 0
