#!/bin/bash

# Find or start a systemtap server
#
# Copyright (C) 2008, 2009 Red Hat Inc.
#
# This file is part of systemtap, and is free software.  You can
# redistribute it and/or modify it under the terms of the GNU General
# Public License (GPL); either version 2, or (at your option) any
# later version.

# This script attempts to find a systemtap server. If one is found, it
# echoes 0 and exits with 0.
#
# Otherwise, it attempts to start a server. If succesful, it echoes the
# process id and exits with 0.
#
# Otherwise, it echoes -1 and exits with 1

# Where are we installed?
exec_prefix=`dirname $0`
exec_prefix=`cd $exec_prefix && pwd`

# Is there a server available?
$exec_prefix/stap-find-servers >/dev/null 2>&1 && echo 0 && exit 0

# No server available, try to start one.
pid=`$exec_prefix/stap-start-server "$@"`
if test $? = 0; then
    echo $pid
    exit 0
fi

# Could not find or start a server
echo "-1"
exit 1
