#!/bin/bash

# Start a systemtap server
#
# Copyright (C) 2008 Red Hat Inc.
#
# This file is part of systemtap, and is free software.  You can
# redistribute it and/or modify it under the terms of the GNU General
# Public License (GPL); either version 2, or (at your option) any
# later version.

# This script attempts to stop a systemtap server with the
# given pid.

# Get the process id.
pid=$1
if test "X$pid" = "X"; then
   echo "Usage: $0 PROCESS_ID" >&2
   exit 1
fi

# Verify that it is a systemtap server
(ps -a | grep stap-serverd | grep -q $pid)
if test $? != 0; then
   echo "$pid is not a systemtap server"
   exit 1
fi

# Try to kill the server
kill -s SIGTERM $pid
