proc test_procedure {} {
    global subdir
    if {$subdir != ""} {
	cd $subdir
    }
    
    
    set flags ""
    foreach filename [lsort [glob *.c]] {
	set file [string range $filename 0 end-2]
	target_compile $filename $file executable $flags
	send_log "Testing ${file}\n"
	set res [exec ./test.tcl $file]
	if {$res == "PASS"} {
	    pass "$file"
	} elseif {$res == "UNSUPP"} {
	    unsupported "$file not supported on this arch"
	} else {
	    fail "$file"
	    send_log "$res\n"
	}
    }
    
    if {$::tcl_platform(machine) == "x86_64"} {
	# on x86_64, test 32-bit and 64-bit binaries
	set flags "additional_flags=-m32"
	foreach filename [lsort [glob *.c]] {
	    set file [string range $filename 0 end-2]
	    target_compile $filename $file executable $flags
	    send_log "Testing 32-bit ${file}\n"
	    set res [exec ./test.tcl $file]
	    if {$res == "PASS"} {
		pass "32-bit $file"
	    } elseif {$res == "UNSUPP"} {
		unsupported "$file not supported on this arch"
	    } else {
		fail "32-bit $file"
		send_log "$res\n"
	    }
	}
    }
    
    if {$subdir != ""} {
	cd ..
    }
}

test_procedure
