# Test linear histogram

set test "linear_under"
set ::result_string {count=100
sum=4950
min=0
max=99
avg=49
value |-------------------------------------------------- count
 1800 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 100
 1900 |                                                     0
 2000 |                                                     0

}

stap_run2 $srcdir/$subdir/$test.stp -DMAXACTION=10000


