#Makefile for SystemTap_Beginners_Guide

XML_LANG	= en-US
DOCNAME		= SystemTap_Beginners_Guide
PRODUCT	= Red_Hat_Enterprise_Linux
BRAND	= RedHat

#OTHER_LANGS	= as-IN bn-IN de-DE es-ES fr-FR gu-IN hi-IN it-IT ja-JP kn-IN ko-KR ml-IN mr-IN or-IN pa-IN pt-BR ru-RU si-LK ta-IN te-IN zh-CN zh-TW
TRANSLATIONS	= $(XML_LANG) $(OTHER_LANGS)

COMMON_CONFIG  = /usr/share/publican
include $(COMMON_CONFIG)/make/Makefile.common

