# Test TCP probes
load_lib "stap_run.exp"
set test "tcptest"

set tcp_tcl "$srcdir/$subdir/tcptest.tcl"
proc tcp_gen { } {
   exec $::tcp_tcl 1 
   return 0
}
set output_header "UID\tPID\tSIZE\tNAME\t\t\tPORT\tSOURCE\t\tRTO\tRCVMSS\tSSTHRES\tCWND\tSTATE\r\n"
set output_rows "((\\d+\t\\d+\t\\d+\t\\S+\t\t\t\\d+\t\\S*\t\\d+\t\\d+\t\\d+\t\\d+\t\\d+)?\r\n){5}"
set output_string "TCP totalbytes: \\d+\r\n$output_header$output_rows"
stap_run $srcdir/$subdir/$test.stp tcp_gen $output_string
