set test "ctime"
set ::result_string {Thu Jan  1 00:00:00 1970
Wed Dec 31 23:59:59 1969
Thu Jan  1 00:00:01 1970
Sat Mar  3 09:46:40 1973
Fri Feb 13 23:31:30 2009
Sat Jan 10 13:37:04 2004
Fri Jul 13 11:01:20 2012
a long, long time ago...
far far in the future...
Fri Dec 13 20:45:52 1901
a long, long time ago...
Tue Jan 19 03:14:07 2038
far far in the future...
a long, long time ago...
far far in the future...}
stap_run2 $srcdir/$subdir/$test.stp
