# Simple function to test that pp() and pn() work

proc opener {} { # the test uses syscall.open -- make sure it happens
    exec cat /dev/null
    return 0;
}

set test "pp"
set file $srcdir/$subdir/pp.stp
set output_string "(kernel\\.function\[^\r\n]*\r\n)+systemtap test success\r\n"
stap_run $test opener $output_string $file $test

set test "pn"
set output_string "syscall\\.open\r\nsystemtap test success\r\n"
stap_run $test opener $output_string $file $test
