#!/usr/bin/tclsh
# -*- tcl -*-

# simple script to build each probe directory

proc usage {} {
  puts "Usage: build \[-v\] \[clean\]"
  exit
}

set clean ""
set verbose ""

foreach arg $argv {
  if {$arg == "clean"} {
    set clean $arg
  } elseif {$arg == "-v"} {
    set verbose $arg
  } else {
    usage
  }
}

set cmd "exec ../build_probe $verbose $clean"

foreach filename [lsort [glob *]] {
  if {$filename != "CVS" && [file isdirectory $filename]} {
    cd $filename
    if {[catch {exec ../build_probe $verbose $clean} res]} {
      puts $res
      exit
    }
    puts $res
    cd ..
  }
}

