# Makefile
PWD     := $(shell pwd)
RT	:= $(PWD)/../..
KVERSION	:= $(shell uname -r)
KDIR	:= /lib/modules/$(KVERSION)/build include

FLAGS := -I $(RT) RELAYFS

DFLAGS := $(FLAGS) -D DEBUG

obj-m := XXX.o

default:
	$(MAKE) V=1 -C $(KDIR) M=$(PWD) RT=$(RT) EXTRA_CFLAGS="$(FLAGS)" modules

debug:
	$(MAKE) V=1 -C $(KDIR) M=$(PWD) RT=$(RT) EXTRA_CFLAGS="$(DFLAGS)" modules


clean:
	/bin/rm -rf *.o *.o.d *.ko *~ *.mod.c .*.cmd .tmp_versions
