#!/bin/bash

KVERSION=`uname -r`
echo $KVERSION
KALLSYMS_LOOKUP_NAME=`grep " kallsyms_lookup_name" /boot/System.map-$KVERSION |awk '{print $1}'`
KALLSYMS_LOOKUP=`grep " kallsyms_lookup$" /boot/System.map-$KVERSION |awk '{print $1}'`

make V=1 -C /lib/modules/`uname -r`/build M=`pwd` modules \
	KALLSYMS_LOOKUP_NAME=0x$KALLSYMS_LOOKUP_NAME \
	KALLSYMS_LOOKUP=0x$KALLSYMS_LOOKUP \
	STP_RUNTIME=`pwd`/../..





