#!/usr/bin/env ruby
load './bench.rb'

# script test to binary print 4 integers
test3 = Stapbench.new("binary printf 4 integers (%b)")
test3.code = "printf(\"%b%b%b%b\", 111,22,333,444)"
test3.run
test3.print
test3.trans = BULK
test3.run
test3.print

# script test to binary print 4 integers
test4 = Stapbench.new("_stp_print_binary 4 integers")
test4.code = "stp_print_binary(4,111,22,333,444)"
test4.run
test4.print
test4.trans = BULK
test4.run
test4.print

