#!/bin/bash

ln -s ../map.h .
ln -s ../map.c .
ln -s ../map-stat.c .
ln -s ../string.c .
ln -s ../string.h .
ln -s ../sym.c .
ln -s ../counter.c .
ln -s ../stat.c .
ln -s ../stat.h .
ln -s ../stat-common.c .
ln -s ../arith.c .
ln -s ../map-gen.c .
ln -s ../pmap-gen.c .
